name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  Presign_URLs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install boto3
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install requests
        shell: bash

      - name: Generate and Publish Presigned URLs
        run: python .github/aws_signer.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Presigned URLs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: presigned-urls
          path: presigned_urls
  build:
    runs-on: ubuntu-latest
    needs: Presign_URLs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Presigned URLs Artifact
        uses: actions/download-artifact@v3
        with:
          name: presigned-urls
          path: presigned_urls

      - name: Print working directory and list files
        run: |
          pwd
          ls -a
          ls -a presigned_urls
          cd presigned_urls
          pwd
          ls -a

      - name: Set up JDK 11 with Maven Cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Build with Maven
        run: mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false -Dtest=AppdomeBuilderTest#testAndroidPrivateSignBuild test clean verify package
      - name: Remove Artifacts
        run: |
          echo "Removing downloaded files..."
          rm -rf downloaded_files
          echo "Artifacts removed."