name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  Presign_URLs:
    runs-on: "ubuntu-latest"
    steps:
    # Your steps for Presign_URLs

  build_android:
    runs-on: ubuntu-latest
    needs: Presign_URLs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Presigned URLs Artifact
        uses: actions/download-artifact@v3
        with:
          name: presigned-urls
          path: presigned_urls
      - name: Set up JDK 11 with Maven Cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Download dependencies
        run: mvn -B dependency:go-offline
      - name: Build and test for Android
        run: mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false clean verify -Dtest=AppdomeBuilderTest#testAndroidPrivateSignBuild package

  build_ios:
    runs-on: ubuntu-latest
    needs: Presign_URLs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Presigned URLs Artifact
        uses: actions/download-artifact@v3
        with:
          name: presigned-urls
          path: presigned_urls
      - name: Set up JDK 11 with Maven Cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Download dependencies
        run: mvn -B dependency:go-offline
      - name: Build and test for iOS
        run: mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false clean verify -Dtest=AppdomeBuilderTest#testAndroidPrivateSignBuild package
